[package]
name = "fun"
version = "0.1.0"
authors = ["Eliott Veyrier <eliott.veyrier@umontpellier.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"

